// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using GV.DomainModel.SharedKernel.Interfaces;
using System;

namespace CoacehlTraining.Core.Entities
{
    public partial class Person //: IAggregateRoot
    {
        public int Id { get; set; }
        public string Dni { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime CreationDate { get; set; }
    }
}